analytics:
  google:
    id: UA-84829010-5

repository: https://github.com/Y-English/Y-English-Blog

timezone: Asia/Shanghai
lang: zh_CN

title: 云英语
description: Y-English
keywords: 云英语, Y-English, Vocanulary Builder, VB, Y-GRE, GRE, Blog, Education, Flipped Classroom
url: http://blog.y-english.org

author: iROCKBUNNY
author_url: http://irockbunny.com
organization: 云英语
organization_url: https://y-english.org

contact: dev[at]y-english[dot]org

image: /images/logo-blue.png
logo: /images/logo-dark.png

permalink: /post/:year/:month/:day/:title/

excerpt_separator: <!--more-->

paginate: 5
paginate_path: /posts/:num/

collections:
  perspective_posts:
    output: true
    permalink: /perspective/post/:name
  academic_posts:
    output: true
    permalink: /academic/post/:name
  feedback_posts:
    output: true
    permalink: /feedback/post/:name

defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: post
      news: true
  - scope:
      path: ""
      type: perspective_posts
    values:
      layout: page
      perspective: true
  - scope:
      path: ""
      type: academic_posts
    values:
      layout: page
      academic: true
  - scope:
      path: ""
      type: feedback_posts
    values:
      layout: page
      feedback: true

plugins:
- jekyll-feed
- jekyll-paginate
- jekyll-seo-tag
- jekyll-sitemap

exclude:
- .gitignore
- .travis.yml
- LICENSE.md
- README.md
- CNAME
- Gemfile
- Gemfile.lock
- script
- vendor