analytics:
  google:
    id: UA-84829010-5

repository: https://github.com/Y-English/Y-English-Live

timezone: Asia/Shanghai
lang: zh_CN

title: 云英语 · Y-English
alias: 云英语
description: 不背单词的GRE工程化解决方案
keywords: 云英语, Y-English, Vocanulary Builder, VB, Y-GRE, GRE, Education, Flipped Classroom
url: https://live.y-english.org

author: iROCKBUNNY
author_url: http://irockbunny.com
organization: 云英语
organization_url: https://y-english.org

contact: dev[at]y-english[dot]org

image: /images/logo-blue.png
logo: /images/logo-dark.png
logo_dark: /images/logo-dark.svg
logo_white: /images/logo-white.svg

permalink: /event/post/:year/:month/:day/:title/

excerpt_separator: <!--more-->

paginate: 5
paginate_path: /event/:num/

collections:
  album_posts:
    output: true
    permalink: /album/post/:name/
  feedback_posts:
    output: true
    permalink: /feedback/post/:name/
  academic_posts:
    output: true
    permalink: /academic/post/:name/
  word_wiki_posts:
    output: true
    permalink: /word-wiki/post/:name/
  gre_review_posts:
    output: true
    permalink: /gre-review/post/:name/

defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: post
      active_key: news
  - scope:
      path: ""
      type: album_posts
    values:
      layout: page
      active_key: album
  - scope:
      path: ""
      type: feedback_posts
    values:
      layout: page
      active_key: feedback
  - scope:
      path: ""
      type: academic_posts
    values:
      layout: page
      active_key: academic
  - scope:
      path: ""
      type: word_wiki_posts
    values:
      layout: page
      active_key: word_wiki
  - scope:
      path: ""
      type: gre_review_posts
    values:
      layout: page
      active_key: gre_review

plugins:
- jekyll-feed
- jekyll-paginate
- jekyll-seo-tag
- jekyll-sitemap

exclude:
- .gitignore
- .travis.yml
- LICENSE.md
- README.md
- CNAME
- Gemfile
- Gemfile.lock
- script
- vendor